#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jenkins"
name = "Jenkins"
description.en = "Extendable continuous integration server"
description.fr = "Serveur d'intégration continue extensible"

version = "2.452.2~ynh2"

maintainers = ["dogusdeniz"]

[upstream]
license = "MIT"
website = "https://jenkins.io"
userdoc = "https://www.jenkins.io/doc/book/"
code = "https://github.com/jenkinsci/jenkins"
cpe = "cpe:2.3:a:cloudbees:jenkins"
fund = "https://www.jenkins.io/donate"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jenkins"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
    [resources.sources.jenkins-plugin-manager]
    url = "https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.13.0/jenkins-plugin-manager-2.13.0.jar"
    sha256 = "ced30bcaa33209478ad43a6f02e5e217415a1f3a37b28d2d044db7b3e96004e5"
    format = "whatever"
    extract = false
    rename = "jenkins-plugin-manager.jar"

    [resources.sources.main]
    url = "https://mirrors.jenkins.io/debian-stable/jenkins_2.452.2_all.deb"
    sha256 = "b29bb56be98051a03044315138ae8cc64cbcd7cfed52542fc4f8c11ec99d3796"
    format = "whatever"
    extract = false
    rename = "jenkins.deb"

    [resources.system_user]
    home = "/var/lib/jenkins"

    [resources.install_dir]
    dir = "/var/lib/jenkins"

    [resources.permissions]
    main.url = "/"
    github_webhook.url = "/github-webhook"
    github_webhook.allowed = "visitors"
    github_webhook.protected = false
    github_webhook.show_tile = false

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = [
        "openjdk-17-jdk\\|openjdk-21-jdk",
        "daemon",
        "net-tools"
    ]
